version: "3"
services: 
    user-service:
        build: .
        ports: 
            - "80:80"
        environment: 
            - "DB_HOST=database"
            - "DB_PORT=3306"
            - "DB_USERNAME=LGZzDYnar6J6"
            - "DB_PASSWORD=WKt9WERFsguniXmCaWSai4MBC2Kxhq"
            - "DB_DATABASE=user-service"
    
    database:
        image: mariadb:10.5
        environment:
            - "MYSQL_RANDOM_ROOT_PASSWORD=1"
            - "MYSQL_USER=LGZzDYnar6J6"
            - "MYSQL_PASSWORD=WKt9WERFsguniXmCaWSai4MBC2Kxhq"
            - "MYSQL_DATABASE=user-service"